### ISSUE TITLE
Upgrade xmlutil

### ISSUE THREAD

**Issue by DRSchlaubi** [rxsto/kommunity#4]
They're on maven central now due to jcenter sunset: https://github.com/pdvrieze/xmlutil/issues/60

**Comment by rxsto** [comment]
The dependency `xmlutil` is now being pulled from maven central (`0.81.2`). The linked pull request will include a full migration away from jcenter & co. We're waiting for `kord.x.commands-runtime-kord` to update to `koin@v3`. The current release `0.4.0-SNAPSHOT` is still using version 2 which is hosted on jcenter.
